<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="MS-20160617BOYN" name="搜索诺基亚、投诉、下订单、精品推荐区" tests="14" failures="5" timestamp="4 Mar 2018 06:24:58 GMT" time="156.428" errors="0">
  <testcase name="Sousuo" time="2.711" classname="cases.Case1"/>
  <testcase name="Sousuo" time="1.525" classname="cases.Case1">
    <failure type="java.lang.AssertionError" message="expected [0] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [1]
	at base.CheckPoint.result(CheckPoint.java:33)
	at cases.Case1.Sousuo(Case1.java:74)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- Sousuo -->
  <testcase name="Sousuo" time="1.455" classname="cases.Case1">
    <failure type="java.lang.AssertionError" message="expected [0] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [2]
	at base.CheckPoint.result(CheckPoint.java:33)
	at cases.Case1.Sousuo(Case1.java:74)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- Sousuo -->
  <testcase name="Sousuo" time="1.42" classname="cases.Case1">
    <failure type="java.lang.AssertionError" message="expected [0] but found [3]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [3]
	at base.CheckPoint.result(CheckPoint.java:33)
	at cases.Case1.Sousuo(Case1.java:74)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- Sousuo -->
  <testcase name="Sousuo" time="1.435" classname="cases.Case1">
    <failure type="java.lang.AssertionError" message="expected [0] but found [4]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [4]
	at base.CheckPoint.result(CheckPoint.java:33)
	at cases.Case1.Sousuo(Case1.java:74)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- Sousuo -->
  <testcase name="Sousuo" time="1.263" classname="cases.Case1"/>
  <testcase name="Sousuo" time="1.385" classname="cases.Case1">
    <failure type="java.lang.AssertionError" message="expected [0] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [1]
	at base.CheckPoint.result(CheckPoint.java:33)
	at cases.Case1.Sousuo(Case1.java:74)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- Sousuo -->
  <testcase name="Sousuo" time="1.155" classname="cases.Case1"/>
  <testcase name="case02" time="34.272" classname="cases.Case2"/>
  <testcase name="case02" time="32.86" classname="cases.Case2"/>
  <testcase name="case03" time="11.899" classname="cases.Case3"/>
  <testcase name="case04" time="14.483" classname="cases.Case4"/>
  <testcase name="case5" time="7.076" classname="cases.Case5"/>
  <testcase name="case06" time="9.575" classname="cases.Case6"/>
</testsuite> <!-- 搜索诺基亚、投诉、下订单、精品推荐区 -->
